image: node:alpine

before_script:
  - "apk update -q && apk add -q openssh-client"
build:
  stage: build
  script:
    - "npm install htmlhint csslint -g > /dev/null"
    - "./scripts/lint.sh"
  except:
    - "master"
  tags:
    - "asprlng"

deploy:
  stage: deploy
  script:
    - "mkdir /root/.ssh"
    - "ssh-keyscan sprlng.de > /root/.ssh/known_hosts"
    - "./scripts/deploy.sh"
  only:
    - "master"
  tags:
    - "asprlng"
