image: node:alpine

before_script:
  - "apk update -q && apk add -q openssh-client"
build:
  stage: build
  script:
    - "npm install htmlhint csslint -g > /dev/null"
    - "./scripts/lint.sh"
  except:
    - "master"
  tags:
    - "asprlng"

deploy:
  stage: deploy
  script:
    - "echo \"${SSH_PRIVATE_KEY}\" > temp_id_rsa"
    - "./scripts/deploy.sh sprlng.de"
  only:
    - "master"
  tags:
    - "asprlng"

build-docker-image:
  stage: build
  script:
    - "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}"
  tags:
    - "asprlng"
