image: node:alpine

stages:
  - "build"
  - "release"
  - "deploy"

build:
  stage: build
  script:
    - "npm install htmlhint csslint -g > /dev/null"
    - "./scripts/lint.sh"
  except:
    - "master"
    - "tags"
  tags:
    - "asprlng"

release:
  stage: release
  script:
    - "echo \"${CI_COMMIT_SHORT_SHA}\""
  only:
    - "master"
  tags:
    - "asprlng"

deploy:
  stage: deploy
  script:
    - "########## Deploying $CI_COMMIT_TAG to prod ##########"
    - "./deploy.sh \"${CI_COMMIT_TAG}\" "
  only:
    - "tags"
  tags:
    - "asprlng"
