image: node:alpine

build:
  stage: build
  script:
    - "npm install htmlhint csslint -g > /dev/null"
    - "./scripts/lint.sh"
  except:
    - "master"
  tags:
    - "asprlng"

deploy:
  stage: deploy
  script:
    - "./scripts/deploy.sh"
  only:
    - "master"
  tags:
    - "asprlng"
